USE [master]
GO
CREATE DATABASE [TibaExam]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TibaExam', FILENAME = N'C:\Program Files\Microsoft SQL Server 2019 Express\MSSQL15.SQLEXPRESS\MSSQL\DATA\TibaExam.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TibaExam_log', FILENAME = N'C:\Program Files\Microsoft SQL Server 2019 Express\MSSQL15.SQLEXPRESS\MSSQL\DATA\TibaExam_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TibaExam] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TibaExam].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TibaExam] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TibaExam] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TibaExam] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TibaExam] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TibaExam] SET ARITHABORT OFF 
GO
ALTER DATABASE [TibaExam] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TibaExam] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TibaExam] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TibaExam] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TibaExam] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TibaExam] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TibaExam] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TibaExam] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TibaExam] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TibaExam] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TibaExam] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TibaExam] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TibaExam] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TibaExam] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TibaExam] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TibaExam] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TibaExam] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TibaExam] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TibaExam] SET  MULTI_USER 
GO
ALTER DATABASE [TibaExam] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TibaExam] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TibaExam] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TibaExam] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TibaExam] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TibaExam] SET QUERY_STORE = OFF
GO
USE [TibaExam]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Favorites](
	[Id] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Url] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TibaExam] SET  READ_WRITE 
GO
